apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 85.215.155.79-85.215.155.79
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool