---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altas-web
  namespace: dev-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-web
  template:
    metadata:
      labels:
        app: atlas-web
    spec:
      containers:
      - name: altas-web
        image: amb0u/react-app:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "https://new-api.atlascmms.com"        
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"    
---
apiVersion: v1
kind: Service
metadata:
  name:  altas-web
  namespace: dev-web
spec:
  selector:
    app: atlas-web
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: altas-web
  namespace: dev-web
spec:
  rules:
  - host: "dev.atlascmms.com"
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: altas-web
            port:
              number: 80